import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Providers from "@/provider/Providers";
import HeaderContainer from "@/app/(main)/_components/HeaderContainer";

export const metadata: Metadata = {
  title: "짠테크",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <HeaderContainer />
          <main className="flex-grow flex items-center justify-center">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
